
services:
  # Qdrant vector database service
  qdrant:
    image: qdrant/qdrant:latest
    container_name: rag-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - rag-network


  # FastAPI backend service
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    # volumes:
    #   - ./backend:/app/backend  # Mount backend code
    container_name: rag-backend
    ports:
      - "8000:8000"
    depends_on:
      - qdrant 
    environment:
      - PYTHONUNBUFFERED=1
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_URL=http://host.docker.internal:11434
    restart: on-failure
    networks:
      - rag-network



  # Streamlit frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # volumes:
    #   - ./frontend:/app/frontend  # Mount frontend code
    container_name: rag-frontend
    depends_on:
      - backend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
      - WEBSOCKET_URL=ws://backend:8000
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    networks:
      - rag-network

# Named volumes
volumes:
  qdrant_data:
    driver: local

# Networks
networks:
  rag-network:
    driver: bridge